services:
  engage:
    image: engage:latest
    build:
      context: .
      dockerfile: engage.dockerfile
    # env_file: ".env"
    ports:
      - "8080:5173"
      # - "7070:7070"
    # environment:
      # - VITE_UPLOAD_SERVER="https://localhost:3000/upload"
    volumes:
      - ./media:/app/media
  upload-server:
    image: upload-server:latest
    build:
      context: .
      dockerfile: upload-server.dockerfile
    volumes:
     - ./media:/usr/src/app/media
    ports:
      - "3000:3000" # for upload server
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD="warmer"
      - MYSQL_DATABASE="engage"
      - MYSQL_USER="engageuser"
      - MYSQL_PASSWORD="engagepassword"
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      # - ./initdb:/docker-entrypoint-initdb.d/