services:
  engage:
    image: engage:latest
    build:
      context: .
      dockerfile: engage.dockerfile
    env_file: ".env"
    ports:
      - "8081:5173"
      # - "7070:7070"
    # environment:
      # - VITE_UPLOAD_SERVER="https://localhost:3000/upload"
    volumes:
      - ./media:/app/media
  upload-server:
    image: upload-server:latest
    build:
      context: .
      dockerfile: upload-server.dockerfile
    volumes:
     - ./media:/usr/src/app/media
    ports:
      - "3000:3000" # for upload server