services:
  engage:
    image: engage:latest
    build:
      context: .
      dockerfile: engage.dockerfile
    ports:
      - "8081:80"
    environment:
      - ENV_VAR_NAME=example_value
    # volumes:
    #   - ./data:/app/data
  upload-server:
    image: upload-server:latest
    build:
      context: .
      dockerfile: upload-server.dockerfile
    ports:
      - "127.0.0.1:3000:3000" # for upload server